server/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls), 
    path("", include("vote.urls")), #vote app 
    # path("account/", include("vs_account.urls")), #account app
    path("accounts/", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/vote/urls.py
from django.urls import path
from . import views

from rest_framework.urlpatterns import format_suffix_patterns #추가

app_name = "vote"

urlpatterns = [
    # 공통
    path("", views.MainView.as_view(), name="main"),
    path("<int:poll_id>/", views.PollDetailView.as_view(), name="detail"),
    path("<int:poll_id>/gender", views.poll_classifyuser, name="poll_classifyuser"),
    path(
        "<int:poll_id>/poll_result_page/<int:uservote_id>/<int:nonuservote_id>",
        views.poll_result_page,
        name="poll_result_page" ,
    ),
    # 유저
    path("like/", views.poll_like, name="like"),
     path("comment_like/", views.comment_like, name="comment_like"),
    path(
        "get-like-status/<int:poll_id>/", views.get_like_status, name="get_like_status"
    ),
    path("mypage/", views.MypageView.as_view(), name="mypage"),
    path(
        "<int:poll_id>/comment/write/", views.comment_write_view, name="comment_write"
    ),
    path("<int:pk>/comment/delete/", views.comment_delete_view, name="comment_delete"),
    path(
        "calculate-nested-count/<int:comment_id>/",
        views.calculate_nested_count,
        name="calculate_nested_count",
    ),
    # path('get_replies/<int:comment_id>/', views.get_replies_view, name='get_replies'),    # 논유저
    # path('<int:poll_id>/<int:nonuservote_id>', views.poll_nonusergender, name='nonusergender'),
    path(
        "<int:poll_id>/<int:nonuservote_id>/mbti",
        views.poll_nonusermbti,
        name="nonusermbti",
    ),
    path(
        "<int:poll_id>/<int:nonuservote_id>/1/1",
        views.poll_nonuserfinal,
        name="nonuserfinal",
    ),
    path(
        "fortune/",
        views.fortune,
        name="fortune",
    ),
    
    #path('api/', views.PollList.as_view(), name='api'),
]

server/vote/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from accounts.models import User

#투표 게시글 DB
class Poll(models.Model): 
    owner = models.ForeignKey(User, on_delete=models.CASCADE,  )
    title = models.TextField()
    content = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)
    poll_like = models.ManyToManyField('accounts.User', blank=True, related_name='likes')
    views_count = models.PositiveIntegerField(default=0)  # 조회 수
    thumbnail = models.ImageField()
    comments = models.PositiveIntegerField(verbose_name='댓글수', default=0)  # 댓글 수    

    def increase_views(self): # 조회수
        self.views_count=self.views_count+1
        self.save()

    # def update_comments_count(self): # 댓글수
    #     self.comments = Comment.objects.filter(poll=self).count()
    #     self.save()
        
    def __str__(self):
        return self.title
    
#투표 선택지 DB
class Choice(models.Model) :
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    image = models.ImageField() 

#회원투표 DB
class UserVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_votes')
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

#비회원투표
class NonUserVote(models.Model):
    MBTI = models.TextField(null= True)
    GENDERS = (
        ('M', '남성'),
        ('W', '여성'),
    )
    gender = models.CharField(verbose_name='성별', max_length=1, choices=GENDERS, null= True)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

#댓글 DB
class Comment(models.Model): 
    user_info = models.ForeignKey(User, on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    comment_like = models.ManyToManyField('accounts.User', blank=True, related_name='comment_like')
   
    # def save(self, *args, **kwargs):
    #     is_new = self.pk is None  # 새로운 댓글인지 확인
    #     super().save(*args, **kwargs)
        
    #     if is_new:  # 새로운 댓글인 경우 댓글 수 업데이트
    #         self.poll.update_comments_count()

    # def delete(self, *args, **kwargs):
    #     super().delete(*args, **kwargs)
    #     self.poll.update_comments_count()
   
    def __str__(self):
        return self.content
    
class Poll_Result(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    total= models.PositiveIntegerField(default=0)
    choice1_man=models.PositiveIntegerField(default=0)
    choice2_man=models.PositiveIntegerField(default=0)
    choice1_woman=models.PositiveIntegerField(default=0)
    choice2_woman=models.PositiveIntegerField(default=0)
    choice1_E=models.PositiveIntegerField(default=0)
    choice2_E=models.PositiveIntegerField(default=0)
    choice1_I=models.PositiveIntegerField(default=0)
    choice2_I=models.PositiveIntegerField(default=0)
    choice1_N=models.PositiveIntegerField(default=0)
    choice2_N=models.PositiveIntegerField(default=0)
    choice1_S=models.PositiveIntegerField(default=0)
    choice2_S=models.PositiveIntegerField(default=0)
    choice1_T=models.PositiveIntegerField(default=0)
    choice2_T=models.PositiveIntegerField(default=0)
    choice1_F=models.PositiveIntegerField(default=0)
    choice2_F=models.PositiveIntegerField(default=0)
    choice1_J=models.PositiveIntegerField(default=0)
    choice2_J=models.PositiveIntegerField(default=0)
    choice1_P=models.PositiveIntegerField(default=0)
    choice2_P=models.PositiveIntegerField(default=0)

server/vote/forms.py
from django import forms

class MBTIForm(forms.Form):
    MBTI_CHOICES = (
        ("INFP", "INFP"),
        ("ENFP", "ENFP"),
        ("INFJ", "INFJ"),
        ("ENFJ", "ENFJ"),
        ("INTJ", "INTJ"),
        ("ENTJ", "ENTJ"),
        ("INTP", "INTP"),
        ("ENTP", "ENTP"),
        ("ISFP", "ISFP"),
        ("ESFP", "ESFP"),
        ("ISFJ", "ISFJ"),
        ("ESFJ", "ESFJ"),
        ("ISTP", "ISTP"),
        ("ESTP", "ESTP"),
        ("ISTJ", "ISTJ"),
        ("ESTJ", "ESTJ"),
    )
    
    mbti = forms.ChoiceField(label="MBTI", choices=MBTI_CHOICES)

server/vote/views.py
import json
import random
import numpy as np
from .models import *
from accounts.models import *
from .fortunes import fortunes
from django.urls import reverse
from django.http import HttpResponse, JsonResponse
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Count
from django.core.exceptions import ObjectDoesNotExist

from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404
from .serializers import *

# 메인페이지
class MainView(APIView):
    # authentication_classes = [SessionAuthentication, BasicAuthentication]
    # permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        if user.is_authenticated and user.custom_active == False:
            authentication_url = reverse("vs_account:email_verification", args=[user.id])
            return redirect(authentication_url)
        if user.is_authenticated:
            if user.gender == "" or user.mbti == "":
                return redirect("vote:update")
        
        polls = Poll.objects.all()
        polls = polls.order_by("-id")
        sort = request.GET.get("sort")
        promotion_polls = Poll.objects.filter(active=True).order_by("-views_count")[:3]

        if sort == "popular":
            polls = polls.order_by("-views_count")  # 인기순
        elif sort == "latest":
            polls = polls.order_by("-id")  # 최신순
        elif sort == "oldest":
            polls = polls.order_by("id")  # 등록순

        page = request.GET.get("page")
        random_poll = random.choice(polls) if polls.exists() else None
        paginator = Paginator(polls, 4)

        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page = 1
            page_obj = paginator.page(page)
        except EmptyPage:
            page = paginator.num_pages
            page_obj = paginator.page(page)

        polls = Poll.objects.all()

        if polls:
            today_poll = polls.last()
        else:
            today_poll = None
        
        phrases = [
            "투표하는 즐거움",
            "나의 투표를 가치있게",
            "나의 취향을 분석적으로",
            "mbti와 통계를 통한 투표 겨루기"
        ]

        random_phrase = random.choice(phrases)

        # Serialize the data
        serialized_polls = PollSerializer(polls, many=True).data

        response_data = {
            "polls": serialized_polls,
            "page_obj": page_obj.number,
            "paginator": {
                "num_pages": paginator.num_pages,
                "count": paginator.count,
            },
            "promotion_polls": PollSerializer(promotion_polls, many=True).data,
            "today_poll": PollSerializer(today_poll).data if today_poll else None,
            "random_phrase": random_phrase
        }

        return Response(response_data)

# 투표 디테일 페이지
class PollDetailView(APIView):
    def get(self, request, poll_id):
        user = request.user

        if user.is_authenticated and user.custom_active == False:
            authentication_url = reverse("vs_account:email_verification", args=[user.id])
            return redirect(authentication_url)

        if user.is_authenticated and (user.gender == "" or user.mbti == ""):
            return redirect("vote:update")

        poll = get_object_or_404(Poll, id=poll_id)

        if user.is_authenticated and user.voted_polls.filter(id=poll_id).exists():
            uservote = UserVote.objects.filter(poll_id=poll_id).get(user=user)
            calcstat_url = reverse("vote:calcstat", args=[poll_id, uservote.id, 0])
            return redirect(calcstat_url)
        else:
            poll.increase_views()  # 게시글 조회 수 증가
            loop_count = poll.choice_set.count()
            loop_time = list(range(0, loop_count))
            # Serialize the Poll object using PollSerializer
            serialized_poll = PollSerializer(poll).data
            context = {
                "poll": serialized_poll,
                "loop_time": loop_time,
            }
            return Response(context)


# 투표 게시글 좋아요 초기 검사
def get_like_status(request, poll_id):
    try:
        poll = Poll.objects.get(id=poll_id)
    except Poll.DoesNotExist:
        return JsonResponse({"error": "해당 투표가 존재하지 않습니다."}, status=404)

    user = request.user
    user_likes_poll = False

    if request.user.is_authenticated:
        if poll.poll_like.filter(id=user.id).exists():
            user_likes_poll = True

    context = {"user_likes_poll": user_likes_poll}
    return JsonResponse(context)


@api_view(['GET', 'POST'])
# @permission_classes([IsAuthenticated])
def poll_like(request):
    serializer = PollLikeSerializer(data=request.data)
    
    if serializer.is_valid():
        poll_id = serializer.validated_data['poll_id']
        try:
            poll = Poll.objects.get(id=poll_id)
        except Poll.DoesNotExist:
            return Response({"error": "해당 투표가 존재하지 않습니다."}, status=status.HTTP_404_NOT_FOUND)

        user = request.user

        if poll.poll_like.filter(id=user.id).exists():
            poll.poll_like.remove(user)
            message = "좋아요 취소"
            user_likes_poll = False
        else:
            poll.poll_like.add(user)
            message = "좋아요"
            user_likes_poll = True

        like_count = poll.poll_like.count()
        context = {
            "like_count": like_count,
            "message": message,
            "user_likes_poll": user_likes_poll,
        }
        return Response(context)
    else:
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# 댓글 좋아요
@login_required
def comment_like(request):
    user= request.user
    if user.is_authenticated and user.custom_active==False:
        authentication_url = reverse("vs_account:email_verification", args=[user.id])
        return redirect(authentication_url)
    if user.is_authenticated :
        if user.gender== "" or user.mbti=="":
            return redirect("vote:update")
    if request.method == "POST":
        req = json.loads(request.body)
        comment_id = req["comment_id"]

        try:
            comment = Comment.objects.get(id=comment_id)
        except Comment.DoesNotExist:
            return JsonResponse({"error": "해당 댓글이 존재하지 않습니다."}, status=404)

        user = request.user
        user_likes_comment = False
        
        if request.user.is_authenticated:
            user_id = user.id
            user_likes_comment = User.objects.get(id=user_id).comment_like.filter(id=comment.id).exists()

            if user_likes_comment:
                comment.comment_like.remove(user)
                message = "좋아요 취소"
            else:
                comment.comment_like.add(user)
                message = "좋아요"

            like_count = comment.comment_like.count()
            context = {
                "like_count": like_count,
                "message": message,
                "user_likes_comment": not user_likes_comment,
            }
            return JsonResponse(context)
        return redirect("/")


class MypageView(APIView):
    def get(self, request):
        user = request.user

        if not user.is_authenticated:
            return Response({"error": "인증되지 않은 사용자입니다."}, status=401)

        if user.is_authenticated and user.custom_active == False:
            authentication_url = reverse("vs_account:email_verification", args=[user.id])
            return redirect(authentication_url)

        if user.is_authenticated:
            if user.gender == "" or user.mbti == "":
                return redirect("vote:update")

        # 사용자의 투표 목록 가져오기
        uservotes = UserVote.objects.filter(user=request.user)

        # 투표 목록을 페이지별로 페이징
        paginator = Paginator(uservotes, 4)
        page = request.GET.get("page")

        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page = 1
            page_obj = paginator.page(page)
        except EmptyPage:
            page = paginator.num_pages
            page_obj = paginator.page(page)

        # 사용자가 좋아하는 투표 목록 가져오기
        polls_like = Poll.objects.filter(poll_like=request.user)
        length_polls_like = len(polls_like)

        # 페이지 객체를 시리얼라이즈
        serializer = PollSerializer(page_obj, many=True)

        context = {
            "uservotes": serializer.data,
            "polls_like": length_polls_like,
            "page_obj": page_obj.number,
            "num_pages": paginator.num_pages,
        }

        return Response(context)

    def put(self, request):
        user = request.user
        if user.is_authenticated and not user.custom_active:
            authentication_url = reverse("vs_account:email_verification", args=[user.id])
            return redirect(authentication_url)

        serializer = UserUpdateSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# 댓글 쓰기
@login_required
def comment_write_view(request, poll_id):
    user= request.user
    if user.is_authenticated and user.custom_active==False:
        authentication_url = reverse("vs_account:email_verification", args=[user.id])
        return redirect(authentication_url)
    if user.is_authenticated :
        if user.gender== "" or user.mbti=="":

server/templates/vote/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=0.8, maximum-scale=1.0" />   
    <!-- 메타태그 -->
    <meta property="og:url" content="https://daily-vs.com/">
    <meta property="og:title" content="DAILY VS">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://ifh.cc/g/jrVAyz.png">
    <meta property="og:description" content="INTP인 그 사람은 뭘 골랐을까? MBTI에 따른 밸런스 게임 통계 사이트">
    <title>Daily VS</title>

    <link rel="stylesheet" href="{%static 'css/style.css'%}?after" />
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
  </head>
  <body>
    <div class="main-container">
      <div id="base-container">
        <nav class="nav-list">
          {% if user.is_authenticated %}
          <a href="{% url 'vs_account:logout' %}" class="nav-login-btn"><img src="{% static 'img/icon/logout.png' %}" /><span class="login-word">로그아웃</span></a>
          {% else %}
          <a href="{% url 'vs_account:login' %}" class="nav-login-btn"><img src="{% static 'img/icon/login.png' %}" /><span class="login-word">로그인</span></a>
          {% endif %}
            <a href="/" id="logo"
              ><img src="{% static 'img/Row.png' %}" class="base-logo"/></a>
            <div class="nav-right">
              <a href="{% url 'vote:fortune' %}" class="nav-fortune"> <img src="{% static 'img/Cookie.png' %}"/></a>
              {% if user.is_authenticated %}
              <a href="{% url 'vote:mypage' %}" class="nav-ham-btn"><img src="{% static 'img/Logged.png'%}" class="hamburger-icon" /></a>
              {% else %}
              <a href="{% url 'vote:mypage' %}" class="nav-ham-btn"><img src="{% static 'img/Unlogged.png'%}" class="hamburger-icon" /></a>
              {% endif %}
            </div>
          </ul>
        </nav>
        <div class="base-block-container">{% block content %} {% endblock %}</div>
      </div>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</html>

server/templates/vote/detail.html
{% extends 'vote/base.html' %} {% load static %} {% block content %}

<div class="vote-detail-container">
  <div class="detail-top">
    <a href="{% url 'vote:main' %}" role="button" class="back-button"
      ><img src="{% static 'img/icon/left_page.png'%}" style="width: 30px" />
      이전 페이지로
    </a>
    <div class="detail-views">
      <span
        ><img src="{% static 'img/icon/view.png'%}" style="width: 20px"
      /></span>
      <span> {{ poll.views_count }} </span>
      <span> views</span>
    </div>
  </div>
  <div class="vote-introduction">
    {% include 'vote/detail/detail-introduction-card.html' %}
  </div>
  <div class="option-container">
    <div>
      <form action="{% url 'vote:classifyuser' poll.id %}" method="POST">
        {% csrf_token %} {% for choice in poll.choice_set.all %}
        <div
          class="detail-option"
          style="background-image: url(../../media/{{choice.image}});"
        >
          <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
            class="choice-input"
          />
          <label for="choice{{ forloop.counter }}"
            >{{ choice.choice_text }}</label
          >
        </div>
        <strong class="vs-font"><span>V</span><span>S</span></strong>
        {% endfor %}
        <input
          type="submit"
          value="투표하기"
          class="vote-submit-btn"
          disabled
        />
      </form>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/detail.js' %}"></script>
  {% endblock %}
</div>

server/templates/vote/detail2.html
{% extends 'vote/base.html' %} {% load static %} {% block content %}

<div class="vote-gender-detail-container">
  <div class="detail-top">
    <a href="{% url 'vote:main' %}" role="button" class="back-button"
      ><img src="{% static 'img/icon/left_page.png'%}" style="width: 30px" />
      이전 페이지로
    </a>
    <div class="detail-views">
      <span
        ><img src="{% static 'img/icon/view.png'%}" style="width: 20px"
      /></span>
      <span> {{ poll.views_count }} </span>
      <span> views</span>
    </div>
  </div>
  <div class="detail2-title">당신의 성별은 ?</div>
  <div class="option-container">
    <div>
      <form
        action="{% url 'vote:nonusermbti' poll.id nonuservote_id %}"
        method="POST"
      >
        {% csrf_token %} {% for choice in gender %}
        <div
          class="gender-detail-option"
          style="background-image: url(../../{{ choice.image }});"
        >
          <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice }}"
            class="gender-choice-input"
          />
          <label for="choice{{ forloop.counter }}">
            {% if choice == 'M' %} 남성 {% elif choice == 'W' %} 여성 {% endif%}
          </label>
        </div>
        {% endfor %}
        <input
          type="submit"
          value="등록하기"
          class="vote-submit-btn"
          disabled
        />
      </form>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static 'js/detail2.js' %}"></script>

  {% endblock %}
</div>

server/templates/vote/detail3.html
{% extends 'vote/base.html' %} {% load static %} {% block content %}

<div class="vote-detail-container">
  <div class="detail-top">
    <a href="{% url 'vote:main' %}" role="button" class="back-button"
      ><img src="{% static 'img/icon/left_page.png'%}" style="width: 30px" />
      이전 페이지로

    </a>
    <div class="detail-views">
      <span
        ><img src="{% static 'img/icon/view.png'%}" style="width: 20px"
      /></span>
      <span> {{ poll.views_count }} </span>
      <span> views</span>
    </div>
  </div>
  <div class="detail2-title">당신의 MBTI는 ?</div>
  <div class="option-container">
    <form id="loginmodal" action="{% url 'vote:nonuserfinal' poll.id nonuservote_id %}" method="POST">
      {% csrf_token %}
      <div class="mbti-every-options">
        <div class="mbti-two-options">
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_EI" value="E" class="mbti-choice-input"/> E</label>
          </div>
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_EI" value="I" class="mbti-choice-input"/> I</label>
          </div>
        </div>
        <div class="mbti-two-options">
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_SN" value="S" class="mbti-choice-input"/> S</label>
          </div>
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_SN" value="N" class="mbti-choice-input"/> N</label>
          </div>
        </div>
        <div class="mbti-two-options">
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_FT" value="F" class="mbti-choice-input"/> F</label>
          </div>
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_FT" value="T" class="mbti-choice-input"/> T</label>
          </div>
        </div>
        <div class="mbti-two-options">
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_JP" value="J" class="mbti-choice-input"/> J</label>
          </div>
          <div class="mbti-detail-option">
            <label><input type="radio" name="choice_JP" value="P" class="mbti-choice-input"/> P</label>
          </div>
        </div>
      </div>
      <div class="what-is-my-mbti"> 내가 선택한 mbti : <span id="selected-mbti"></span></div>
      <input type="hidden" id="selected-mbti-input" name="selected_mbti" value="" />
      <input type="button" data-bs-toggle="modal" href="#exampleModal" value="등록하기" class="vote-submit-btn" disabled />
    </form>
  </div>
</div>

<div class="modal fade" id="exampleModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="justify-content:center; font-size: 18px; padding-top: 25px;">
        <p> 로그인을 하시면 <span class="modal-logo">Daily VS</span>에서 </br> 더 많은 기능을 사용하실 수 있어요!</p>
      </div>
      <div class="modal-footer" style="display:flex; justify-content: space-around;">
        <button type="button" class="btn" style="background-color: #457c9e; color:white" id="submitForm">그냥 투표하기</button>
        <a type="button" class="btn" href="{% url 'vs_account:login' %}" style="background-color:#ff495a; text-decoration:none; color:white;"> 로그인 하기 </a>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/detail3.js' %}"></script>
<script>
  // 진행 버튼 클릭 시 폼 제출
  document.getElementById("submitForm").addEventListener("click", function () {
      console.log('33')
      document.getElementById("loginmodal").submit();
  });
</script>
{% endblock %}

server/templates/vote/footer.html
{% extends 'vote/base.html' %} {% load static %} {% block content %}

<div class="ham-footer">
    <div>made by Team VS</div>
    <div>social community</div>
    <div>dev</div>
    <div>김정곤 | 곽민경 | 조성민 | 송우진 | 왕한솔</div>
</div>

{% endblock %}

server/templates/vote/list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <a href="{% url 'vs_account:login' %}"> 로그인 </a>
    <a href="{% url 'vs_account:logout' %}"> 로그아웃 </a>
    <a href="{% url 'vs_account:signup' %}"> 회원가입 </a>

    <ul>
    {% for poll in polls %}
    <li>
        <a href="{% url 'vote:detail' poll.id %}">
        {{poll.title}}
        {% if not poll.active%} 
        {% endif %}
        </a>
    </li>
    </ul>
    {% endfor %} 
     <ul>
    {% for page in page_obj %}
    <li>
        <a href="{% url 'vote:detail' page.id %}">
        {{ page.title}}
        {% if not page.active%} 
        {% endif %}
        </a>
    </li>
    </ul>
    {% endfor %}
    <br/>
    {% for page in paginator.page_range %}
    <ul>
        <li>
        <a href="?page={{ page}}">{{page}}</a>
        </li>
        {% endfor %}
    </ul> 
</body>
</html>